import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import data from '../data/about.json'
import { useState } from 'react'
import Link from 'next/link'

export default function About() {

    const [information,setInformation] = useState([...data])
    console.log(data);

    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.navbar}>
                    <Image 
                        className={styles.Logo} 
                        src="/logo.png"
                        width={100}
                        height={100} />
                    <Link href="/" className={styles.home}>Home</Link>
                    <Link href="about" className={styles.about}>About</Link>
                </div>

                <div className={styles.companions}>
                    <h1 className={styles.title}>Companions</h1>
                    {information && information.map((info, index) => {
                        return(
                            <div className={styles.characters}>
                                <div className={styles.charactersContent}>
                                    <img className={styles.image}src={info.img}/>
                                    <br/><br/><br/>
                                    <h1 className={styles.name}>{info.name}</h1>
                                    <p className={styles.text}>Race: {info.race}</p>
                                    <p className={styles.text}>Occupation: {info.occupation}</p>
                                    <p className={styles.text}>Talents: {info.talents}</p>
                                    <p className={styles.text}>Tags: {info.tags}</p>
                                </div>
                            </div>
                        )
                        
                    })}
                        
                </div>
            </main>
        </>
    )
}