import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navbar}>
          <Image 
            className={styles.Logo} 
            src="/logo.png"
            width={100}
            height={100} />
          <Link href="/" className={styles.home}>Home</Link>
          <Link href="about" className={styles.about}>About</Link>
        </div>

        <div className={styles.content}>
          <Image
            className={styles.image1}
            src="/image-1.jpeg"
            width={700}
            height={1000}
          />
          <div className={styles.box}>
            <p className={styles.text}>Divinity: Original Sin II is the sixth game in the Divinity series and indirect sequel to Divinity: Original Sin: an isometric, single-player or multiplayer fantasy RPG with tactical turn-based combat. The central theme of the game is "your origins affect who you are and what chances you get in life."</p>
            <Image
            className={styles.image2}
            src="/image-2.jpeg"
            width={500}
            height={300}
            />
          </div>
          <div className={styles.box}>
            <Image
            className={styles.image3}
            src="/image-3.jpeg"
            width={500}
            height={300}
            />
            <p className={styles.text}>The Divine is dead. The Void approaches. And the powers lying dormant within you are soon to awaken. Choose your role in a BAFTA-winning story, and explore a world that reacts to who you are, and the choices you make. With five races to choose from, and an adventure playable solo or as a party of up to four, lay waste to an oppressive order in a world afraid of magic. Become the God the world so desperately needs.</p>
          </div>
        </div>
      </main>
    </>
  )
}
